<a href="https://colab.research.google.com/github/Juanje932/Diplomado_IAJUAN/blob/master/mesademacetas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [5]:
# cargamos las 4 combinaciones de las compuertas XOR
training_data = np.array([[1,0,0,0,0,0,0],[1,1,0,0,0,0,0],[0,0,1,0,0,0,0],[0,0,0,1,0,0,0],[0,0,0,0,1,0,0],[0,0,0,1,1,0,0],[1,1,1,0,0,0,0],[0,0,0,0,0,0,1]])

# y estos son los resultados que se obtienen, en el mismo orden
target_data = np.array([[[1],[0],[0],[0],[0]],[[1],[1],[0],[0],[0]],[[1],[1],[1],[0],[0]],[[0],[0],[1],[0],[0]],[[0],[0],[0],[1],[0]],[[0],[0],[0],[0],[1]],[[1],[1],[1],[0],[0]],[[0],[0],[0],[0],[0]]])

In [6]:
print(training_data)

[[1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 1 1 0 0]
 [1 1 1 0 0 0 0]
 [0 0 0 0 0 0 1]]


In [7]:
print(target_data)

[[[1]
  [0]
  [0]
  [0]
  [0]]

 [[1]
  [1]
  [0]
  [0]
  [0]]

 [[1]
  [1]
  [1]
  [0]
  [0]]

 [[0]
  [0]
  [1]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [1]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [1]]

 [[1]
  [1]
  [1]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]
  [0]]]


In [8]:
# definimos una arquitectura de una red neuronal
model = Sequential()
model.add(Dense(16, input_dim=7, activation='relu'))
model.add(Dense(5, activation='sigmoid'))

In [9]:
model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['binary_accuracy'])

In [10]:
model.fit(training_data, target_data,epochs=500 )

Epoch 1/500
1/1 [==============================] - 1s 706ms/step - loss: 0.2538 - binary_accuracy: 0.5500
Epoch 2/500
1/1 [==============================] - 0s 10ms/step - loss: 0.2530 - binary_accuracy: 0.5500
Epoch 3/500
1/1 [==============================] - 0s 10ms/step - loss: 0.2521 - binary_accuracy: 0.5500
Epoch 4/500
1/1 [==============================] - 0s 11ms/step - loss: 0.2513 - binary_accuracy: 0.5500
Epoch 5/500
1/1 [==============================] - 0s 10ms/step - loss: 0.2504 - binary_accuracy: 0.5500
Epoch 6/500
1/1 [==============================] - 0s 9ms/step - loss: 0.2496 - binary_accuracy: 0.5500
Epoch 7/500
1/1 [==============================] - 0s 11ms/step - loss: 0.2488 - binary_accuracy: 0.5500
Epoch 8/500
1/1 [==============================] - 0s 11ms/step - loss: 0.2479 - binary_accuracy: 0.5500
Epoch 9/500
1/1 [==============================] - 0s 12ms/step - loss: 0.2471 - binary_accuracy: 0.5500
Epoch 10/500
1/1 [==============================] - 0s 

In [11]:
#Evaluamos el modelo
scores = model.evaluate(training_data, target_data)

1/1 [==============================] - 0s 154ms/step - loss: 0.0302 - binary_accuracy: 1.0000


In [12]:
print(model.predict(training_data).round())

1/1 [==============================] - 0s 76ms/step
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
